language: go
sudo: required
go:
    - "1.9"
env:
  global:
    - CUDA_VERSION="10.0"
    - CUDA_PKG_VERSION="130-1"
    - CUDA_PKG=cuda-repo-ubuntu1404_${CUDA_VERSION}.${CUDA_PKG_VERSION}_amd64.deb
    - CUDA_LIB_LOCAL=${HOME}/cuda_lib_${CUDA_VERSION}_${CUDA_PKG_VERSION}
    - CUDA_HOME=${CUDA_LIB_LOCAL}
    - PATH=${PATH}:${CUDA_HOME}/bin:${GOPATH}/bin:${CUDA_HOME}/nvvm/bin
    - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${TRAVIS_HOME}/gopath/src/github.com/uber/aresdb/lib
    - NVCCFLAGS="-ldir ${CUDA_HOME}/nvvm/libdevice -noprof -I ${CUDA_HOME}/include/ -L ${CUDA_HOME}/lib64"
    - GTEST_ROOT=./build/googletest
cache: 
  directories:
    - lib
    - gtest

cache:
  directories:
  - $CUDA_LIB_LOCAL

# safelist
branches:
  only:
    - master
install:
  - .travis/install_cuda.sh
  - .travis/install_golang_tools.sh
  - .travis/install_clang_tools.sh
script:
  - make lint
  - make travis
after_success:
  # exclude query/expr from coverage
  - rm query/expr/expr.coverprofile
  # generate coverage output file
  - gover . coverage.out
  # send to coverall
  - goveralls -coverprofile=coverage.out -service=travis-ci 
  # send to codecov.io
  - mv coverage.out coverage.txt
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - .travis/cleanup.sh
